{% set name = "luts" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/luts-{{ version }}.tar.gz
  sha256: 2a96c685c31c4567bb164cd846ab5344d8e42a582c04826da1170e0832368466

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - xarray
    - netcdf4
    - pyhdf

test:
  imports:
    - luts
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hygeos/luts
  summary: Multidimensional labeled arrays and datasets in Python, similar to xarray.
  license: Apache-2.0
  license_url: https://github.com/hygeos/luts/blob/master/LICENSE.TXT
  license_file: LICENSE.TXT
  dev_url: https://github.com/hygeos/luts

extra:
  recipe-maintainers:
    - Mustapha-hygeos
    - fsteinmetz
